include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - android/

linter:
  rules:
    public_member_api_docs: false
    avoid_setters_without_getters: false
    use_if_null_to_convert_nulls_to_bools: false
