name: projeto_crianca
description: Esse projeto tem como intenção auxiliar as famílias de crianças/adolescentes autistas a melhorar a comunicação (não verbal) através de atividades pedagógicas adaptadas para as crianças.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.7.3"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_auth: ^4.1.5
  cloud_firestore: ^4.1.0
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.6
  firebase_database: ^10.0.6
  firebase_analytics: ^10.0.6
  flutter_launcher_icons: ^0.11.0
  flame: ^1.3.0
  google_fonts: ^3.0.1
  ionicons: ^0.2.1
  google_sign_in: ^5.4.1
  flutter_svg: ^1.1.5
  url_launcher: ^6.1.5
  http: ^0.13.5
  dio: ^4.0.6
  flutter_facebook_auth: ^5.0.6
  flutter_layout_grid: ^2.0.1
  carousel_slider: ^4.1.1
  flame_audio: ^1.3.1
  vibration: ^1.7.6
  contained_tab_bar_view: ^0.8.0
  flame_svg: ^1.5.0
  google_maps_flutter: ^2.2.1
  location: ^4.4.0
  geolocator: ^9.0.2
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  flutter_config: ^2.0.0
  maps_launcher: ^2.0.1
  flutter_bloc: ^8.1.1
  flame_bloc: ^1.8.2
  equatable: ^2.0.5
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # app launch icons
    - assets/icon.png
    - assets/adaptive-icon.png
    - assets/login.png
    # app icons
    - assets/icons/
    # avatar icons - eyes
    - assets/avatar/eye/
    # avatar icons - hair
    - assets/avatar/hair/
    # avatar icons - accessories
    - assets/avatar/objects/
    # avatar icons - mouth
    - assets/avatar/smile/
    # other images
    - assets/profile-cover.jpg
    # game images
    - assets/images/alphabet/
    - assets/images/encaixar/
    # game images - sombra
    - assets/images/sombra/
      # game images - puzzle
    - assets/images/puzzle/
    # game audios
    - assets/audio/games/encaixar/
    - assets/audio/games/parDeCores/
    - assets/audio/games/puzzle/
    - assets/audio/games/sombra/
    # routines
    - assets/images/routines/
    # expressions
    - assets/images/expressions/
    - assets/images/memoryGame/
    - assets/images/parDeCores/
    - assets/images/puzzle/
    - assets/images/routines/
    - assets/images/sombra/
    # game audios
    - assets/audio/games/encaixar/
    - assets/audio/games/parDeCores/
    - assets/audio/games/puzzle/
    - assets/audio/games/sombra/
    # activities audios
    - assets/audio/activities/alphabet/
    - assets/audio/activities/numbers/
    # google fonts
    - assets/google_fonts/
    # maps-styles
    - assets/map_styles/normal.json
    - assets/map_styles/dark.json
    - assets/map_styles/pin_map.png
    - assets/map_styles/pin_map_dark.png
    # .env
    - .env

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/adaptive-icon.png"
  adaptive_icon_background: "#FFFFFF"
  web:
    generate: true
    image_path: "assets/adaptive-icon.png"
    background_color: "#FFFFFF"
    theme_color: "#00A7DF"
  windows:
    generate: true
    image_path: "assets/adaptive-icon.png"
    icon_size: 256
