name: projeto_crianca
description: Esse projeto tem como intenção auxiliar as famílias de crianças/adolescentes autistas a melhorar a comunicação (não verbal) através de atividades pedagógicas adaptadas para as crianças.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0-197.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_auth: ^3.8.0
  cloud_firestore: ^3.4.7
  firebase_core: ^1.22.0
  firebase_storage: ^10.3.8
  firebase_database: ^9.1.4
  firebase_analytics: ^9.3.4
  flutter_launcher_icons: ^0.10.0
  flame: ^1.3.0
  google_fonts: ^3.0.1
  ionicons: ^0.2.1
  google_sign_in: ^5.4.1
  flutter_svg: ^1.1.5
  url_launcher: ^6.1.5
  http: ^0.13.5
  dio: ^4.0.6
  flutter_facebook_auth: ^4.4.1+1
  flutter_layout_grid: ^2.0.1
  carousel_slider: ^4.1.1
  flame_audio: ^1.3.1
  vibration: ^1.7.6
  contained_tab_bar_view: ^0.8.0
  google_maps_flutter: ^2.2.1
  location: ^4.4.0
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # app launch icons
    - assets/icon.png
    - assets/adaptive-icon.png
    - assets/login.png
    # app icons
    - assets/icons/avatarM.png
    - assets/icons/avatarF.png
    - assets/icons/activities-icon.png
    - assets/icons/games-icon.png
    - assets/icons/settings-icon.png
    - assets/icons/local-icon.png
    - assets/icons/encaixarIcon.png
    - assets/icons/quebraCabecaIcon.png
    - assets/icons/routines-icon.png
    - assets/icons/expressions-icon.png
      # avatar icons - eyes
    - assets/avatar/eye/cheeryEyes.png
    - assets/avatar/eye/confusedEyes.png
    - assets/avatar/eye/normalEyes.png
    - assets/avatar/eye/sleepyEyes.png
    - assets/avatar/eye/starstruckEyes.png
    - assets/avatar/eye/winkingEyes.png
    # avatar icons - hair
    - assets/avatar/hair/bowlCutHair.png
    - assets/avatar/hair/froBun.png
    - assets/avatar/hair/shortHair.png
    - assets/avatar/hair/shortHairCurly.png
    - assets/avatar/hair/straightHair.png
    - assets/avatar/hair/wavyBob.png
    # avatar icons - accessories
    - assets/avatar/objects/catEars.png
    - assets/avatar/objects/clownNose.png
    - assets/avatar/objects/faceMask.png
    - assets/avatar/objects/glasses.png
    - assets/avatar/objects/sailormoonCrown.png
    - assets/avatar/objects/sunglasses.png
    # avatar icons - mouth
    - assets/avatar/smile/awkwardSmile.png
    - assets/avatar/smile/braces.png
    - assets/avatar/smile/gapSmile.png
    - assets/avatar/smile/kawaii.png
    - assets/avatar/smile/openedSmile.png
    - assets/avatar/smile/teethSmile.png
    # other images
    - assets/profile-cover.jpg
    # game images - encaixar
    - assets/images/encaixar/body.png
    - assets/images/encaixar/engine.png
    - assets/images/encaixar/foguete.png
    - assets/images/encaixar/head.png
    - assets/images/encaixar/lowerWings.png
    - assets/images/encaixar/upperWings.png
    # game audios - encaixar
    - assets/audio/encaixar/background.mp3
    # routines
    - assets/images/routines/1Acordar.png
    - assets/images/routines/2EscovarOsDentes.png
    - assets/images/routines/3TomarBanho.png
    - assets/images/routines/4CafeDaManha.png
    - assets/images/routines/5UsarBanheiro.png
    - assets/images/routines/6IrParaEscola.png
    - assets/images/routines/7Estudar.png
    - assets/images/routines/8PraticarEsportes.png
    - assets/images/routines/9Dormir.png
    # expressions
    - assets/images/expressions/1Alegre.png
    - assets/images/expressions/2Confuso.png
    - assets/images/expressions/3EmDuvida.png
    - assets/images/expressions/4EstouBem.png
    - assets/images/expressions/5Feliz.png
    - assets/images/expressions/6Infeliz.png
    - assets/images/expressions/7Triste.png
    - assets/images/expressions/8Raiva.png
    - assets/images/expressions/9Surpreso.png
    # google fonts
    - assets/google_fonts/

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/adaptive-icon.png"
  adaptive_icon_background: "#FFFFFF"
  web:
    generate: true
    image_path: "assets/adaptive-icon.png"
    background_color: "#FFFFFF"
    theme_color: "#00A7DF"
  windows:
    generate: true
    image_path: "assets/adaptive-icon.png"
    icon_size: 256
