name: projeto_crianca
description: Esse projeto tem como intenção auxiliar as famílias de crianças/adolescentes autistas a melhorar a comunicação (não verbal) através de atividades pedagógicas adaptadas para as crianças.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0-197.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_auth: ^3.8.0
  cloud_firestore: ^3.4.7
  firebase_core: ^1.22.0
  firebase_storage: ^10.3.8
  firebase_database: ^9.1.4
  firebase_analytics: ^9.3.4
  flutter_launcher_icons: ^0.10.0
  flame: ^1.3.0
  google_fonts: ^3.0.1
  ionicons: ^0.2.1
  google_sign_in: ^5.4.1
  flutter_svg: ^1.1.5
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/adaptive-icon.png
    - assets/login.png
    - assets/icons/avatarM.png
    - assets/icons/avatarF.png
    - assets/icons/activities-icon.png
    - assets/icons/games-icon.png
    - assets/icons/settings-icon.png
    - assets/icons/local-icon.png

  fonts:
    - family: Noto
      fonts:
        - asset: assets/fonts/NotoSans-Black.ttf
        - asset: assets/fonts/NotoSans-BlackItalic.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
        - asset: assets/fonts/NotoSans-ExtraBold.ttf
        - asset: assets/fonts/NotoSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/NotoSans-ExtraLight.ttf
        - asset: assets/fonts/NotoSans-ExtraLightItalic.ttf
        - asset: assets/fonts/NotoSans-Italic.ttf
        - asset: assets/fonts/NotoSans-Light.ttf
        - asset: assets/fonts/NotoSans-LightItalic.ttf
        - asset: assets/fonts/NotoSans-Medium.ttf
        - asset: assets/fonts/NotoSans-MediumItalic.ttf
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-SemiBold.ttf
        - asset: assets/fonts/NotoSans-SemiBoldItalic.ttf
        - asset: assets/fonts/NotoSans-Thin.ttf
        - asset: assets/fonts/NotoSans-ThinItalic.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/adaptive-icon.png"
  adaptive_icon_background: "#FFFFFF"
  web:
    generate: true
    image_path: "assets/adaptive-icon.png"
    background_color: "#FFFFFF"
    theme_color: "#00A7DF"
  windows:
    generate: true
    image_path: "assets/adaptive-icon.png"
    icon_size: 256
