name: projeto_crianca
description: Esse projeto tem como intenção auxiliar as famílias de crianças/adolescentes autistas a melhorar a comunicação (não verbal) através de atividades pedagógicas adaptadas para as crianças.

publish_to: "none"

version: 0.1.0+0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  audioplayers: ^5.1.0
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.1.0
  confetti: ^0.7.0
  contained_tab_bar_view: ^0.8.0
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  equatable: ^2.0.5
  firebase_analytics: ^10.0.6
  firebase_auth: ^4.1.5
  firebase_core: ^2.3.0
  firebase_database: ^10.0.6
  firebase_storage: ^11.0.6
  flame: ^1.3.0
  flame_audio: ^2.0.2
  flame_bloc: ^1.8.2
  flame_svg: ^1.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_config: ^2.0.0
  flutter_facebook_auth: ^6.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_layout_grid: ^2.0.1
  flutter_svg: ^2.0.6
  geolocator: ^10.1.0
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.2.1
  google_sign_in: ^6.1.2
  http: ^1.1.0
  ionicons: ^0.2.1
  location: ^5.0.3
  maps_launcher: ^2.0.1
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  url_launcher: ^6.1.5
  vibration: ^1.7.6
  video_player: ^2.6.0
  video_player_web: ^2.0.15

dev_dependencies:
  flame_lint: ^1.1.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/google_fonts/
    - assets/map_styles/
    #avatar
    - assets/avatar/eye/
    - assets/avatar/hair/
    - assets/avatar/objects/
    - assets/avatar/smile/
    #activities images
    - assets/images/routines/
    - assets/images/expressions/
    - assets/images/alphabet/
    - assets/images/numbers/
    #games images
    - assets/images/memoryGame/
    - assets/images/encaixar/
    - assets/images/sombra/
    - assets/images/puzzle/
    - assets/images/parDeCores/

    #activities audios
    - assets/audio/activities/alphabet/
    - assets/audio/activities/numbers/
    #games audios
    - assets/audio/games/encaixar/
    - assets/audio/games/sombra/
    - assets/audio/games/puzzle/
    - assets/audio/games/parDeCores/
    #other audios
    - assets/audio/
    # .env
    - .env

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/adaptive-icon.png"
  adaptive_icon_background: "#FFFFFF"
  web:
    generate: true
    image_path: "assets/adaptive-icon.png"
    background_color: "#FFFFFF"
    theme_color: "#00A7DF"
  windows:
    generate: true
    image_path: "assets/adaptive-icon.png"
    icon_size: 256

flutter_native_splash:
  color: "#ffffff"
  android_12:
    color: "#ffffff"
